package automod_legacy

// These words are listed in in alphabethical order.
var BuiltinSwearWords = map[string]bool{
	"anal":        true,
	"anus":        true,
	"arse":        true,
	"ass":         true,
	"b1tch":       true,
	"ballsack":    true,
	"bastard":     true,
	"bitch":       true,
	"biatch":      true,
	"blowjob":     true,
	"bollock":     true,
	"bollok":      true,
	"boner":       true,
	"boob":        true,
	"boobs":       true,
	"buttplug":    true,
	"clitoris":    true,
	"cock":        true,
	"cum":         true,
	"cunt":        true,
	"dick":        true,
	"dildo":       true,
	"dyke":        true,
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        true,
	"fucks":       true,
	"fudgepacker": true,
	"امك شرموطة":    true,
	"امك قحبة":        true,
	"امك متناكة":        true,
	"امك متناكه":        true,
	"كسمينك":     true,
	"احطه فيك":       true,
	"يبنت العرص":  true,
	"يبنت الوسخة":        true,
	"يبن الوسخة":      true,
	"يبنت القحبة":       true,
	"يبن القحبة":       true,
	"قحبة":        true,
	"كسمين امك":        true,
	"كسمين امك":        true,
	"كس امك":       true,
	"انيك امك":     true,
	"نيك امك":         true,
	"عـرص":        true,
	"خـول":        true,
	"عرص":        true,
	"خول":      true,
	"انيكك":       true,
	"انيك":         true,
	"زبـي":      true,
	"زبي":    true,
	"شرموطه":      true,
	"شرموطة":        true,
	"يبنت الشرموطة":        true,
	"يبن الشرموطة":      true,
	"ميتين":        true,
	"يلعن":       true,
	"يلعن ميتين امك":        true,
	"طيزك":       true,
	"كسك":     true,
	"كسختك":        true,
	"يلعن دين امك":      true,
	"كـسمك":       true,
	"يبن المتناكة":       true,
	"كسمك"         true,
	"شرموط"        true,
}
